name: Push SBOM Artifact to sbom-manager Repository

on:
  workflow_run:
    workflows: ["Generate SBOM and Store Artifact"]
    types:
      - completed

jobs:
  push-to-manager:
    runs-on: ubuntu-latest

    steps:
      - name: Download SBOM Artifact
        uses: actions/download-artifact@v4
        with:
          name: sbom-report
          path: ./sboms

      - name: Verify Artifact
        run: ls -lh ./sboms

      - name: Push SBOM to sbom-manager
        env:
          TOKEN: ${{ secrets.SBOM_PUSH_TOKEN }}
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "GitHub Actions Bot"

          echo "📦 Cloning sbom-manager repo..."
          git clone https://x-access-token:${TOKEN}@github.com/mrpraveenpr/sbom-manager.git
          
          echo "📁 Creating target folder..."
          mkdir -p sbom-manager/sboms/nodejs-bookstore-api

          echo "📋 Copying SBOM artifact..."
          cp ./sboms/sbom.json sbom-manager/sboms/nodejs-bookstore-api/sbom.json

          cd sbom-manager
          git add .
          git commit -m "Add SBOM from nodejs-bookstore-api - $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main
